api:
  url:
    - https://www.alphavantage.co/query?
  key:
    - LEP0XRATU8LATEQ7
job:
  params:
    symbols:
      - MSFT
      - AAPL
    interval:
      - 15min
    function:
      - TIME_SERIES_INTRADAY
    content:
      - full
    cron:
      -